apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: "{{ .Values.name }}-postgresql"
spec:
  ports:
  - name: postgresql
    nodePort: 0
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: "{{ .Values.name }}-postgresql"
    deploymentconfig: "{{ .Values.name }}-postgresql"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

