{{- if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  PARTICIPANTS_POSTGRESQL_DATABASE: {{ .Values.db.name }}
  PARTICIPANTS_POSTGRESQL_PASSWORD: {{ .Values.db.password }}
  PARTICIPANTS_POSTGRESQL_USER: {{ .Values.db.user }}
  PARTICIPANTS_POSTGRESQL_URL: {{ .Values.db.url }}
  ENGAGEMENT_API_URL: {{ .Values.api.engagement }}
  GITLAB_API_URL: {{ .Values.api.gitlab }}
  GITLAB_TOKEN: {{ .Values.tokens.gitlab }}

{{- end }}
