name: lodestar-participants
development: true

imageName: "lodestar-participants"
imageTag: "latest"

builderImage: registry.access.redhat.com/ubi8/openjdk-11
builderImageTag: 1.3

servicePort: 8080

git:
  uri: https://github.com/rht-labs/lodestar-participants.git
  ref: main

db:
  version: 12
  user: sourdough
  password: bread
  name: participantsdb
  adminPassword: password
  url: jdbc:postgresql://localhost:5432/participantsdb

api:
  gitlab: http://gitlab.com
  engagement: http://git-api:8080

tokens:
  webhook: nope
  gitlab: nope
